# Reference https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib','node_modules']
test = 'test/foundry'
cache_path  = 'forge-cache'
optimizer = true
optimizer_runs = 200
solc = "0.8.9"

[invariant]
runs = 256
depth = 32
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

